parameters:
#    tsj_aulas_mentor_alimentos.example.class: tsj\AulasMentor\AlimentosBundle\Example

services:
#    tsj_aulas_mentor_alimentos.example:
#        class: %tsj_aulas_mentor_alimentos.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
